# @example=### Basic example
# steps:
#   - id: documenter
#     name: "Generate document"
#     uses: gizumon/github-actions-documenter@main

# @example=### Example with parameters
# steps:
#   - id: documenter
#     name: "Generate document"
#     uses: gizumon/github-actions-documenter@main
#     with:
#       target-filepaths: |
#         action.yml
#         .github/workflows/github-actions-documenter.yml
#       should-skip-generate-agenda: true
#       should-skip-generate-custom-actions: false
#       should-skip-generate-reusable-workflows: false

name: 'GitHub Actions documenter'
description: 'Auto documentation for Github Actions workflows'
author: 'tomoatsu.sekikawa'

branding:
  icon: 'book-open'
  color: 'green'

inputs:
  target-filepaths:
    required: false
    default: ""
    description: |
      Target filepaths for generating Custom Actions and Reusable Workflows.
      If not specified, all Custom Actions and Reusable Workflows files in the repository will be documented. (default: "")
  should-skip-generate-agenda:
    required: false
    default: "false"
    description: |
      If true, skip generating Agenda document. (default: false)
  should-skip-generate-custom-actions:
    required: false
    default: "false"
    description: |
      If true, skip generating Custom Actions document. (default: false)
  should-skip-generate-reusable-workflows:
    required: false
    default: "false"
    description: |
      If true, skip generating Reusable Workflows document. (default: false)


outputs:
  output:
     description: 'GitHub Actions markdown documents including Custom Actions and Reusable Workflows'
  agenda-ca:
    description: 'Agenda for Custom Actions markdown documents'
  output-ca:
    description: 'Custom Actions markdown documents'
  agenda-rw:
    description: 'Agenda for Reusable Workflows markdown documents'
  output-rw:
    description: 'Reusable Workflows markdown documents'
  # output-filepath:
  #   required: true
  #   default: "README.md"
  #   description: 'Filepath to write the reusable workflow documentation. (default: README.md)'
  # github-base-url:
  #   required: false
  #   default: "https://api.github.com"
  #   description: 'GitHub Host domain (Support for GitHub Enterprise)'
  # overwrite:
  #   required: false
  #   default: "false"
  #   description: 'If true, overwrite the filepath file. (default: false)'
  # make-pull-request:
  #   required: false
  #   default: "false"
  #   description: 'If true, make a pull request to ref branch. If false, directly push generated doc to ref branch. (default: false)'
  # generate-only:
  #   required: false
  #   default: "false"
  #   description: 'Generate document and set output result only. (default: false)'

runs:
  using: 'node16'
  main: 'dist/index.js'
