# @example=### Basic example
# steps:
#   - id: documentator
#     name: "Generate document"
#     uses: gizumon/github-actions-documenter/.github/workflows/github-actions-documenter.yml@main

name: 'GitHub Actions documenter'
description: 'Auto documentation for Github Actions workflows'
author: 'tomoatsu.sekikawa'

branding:
  icon: 'book-open'
  color: 'green'

# inputs:
  # output-filepath:
  #   required: true
  #   default: "README.md"
  #   description: 'Filepath to write the reusable workflow documentation. (default: README.md)'
  # github-base-url:
  #   required: false
  #   default: "https://api.github.com"
  #   description: 'GitHub Host domain (Support for GitHub Enterprise)'
  # overwrite:
  #   required: false
  #   default: "false"
  #   description: 'If true, overwrite the filepath file. (default: false)'
  # make-pull-request:
  #   required: false
  #   default: "false"
  #   description: 'If true, make a pull request to ref branch. If false, directly push generated doc to ref branch. (default: false)'
  # generate-only:
  #   required: false
  #   default: "false"
  #   description: 'Generate document and set output result only. (default: false)'

outputs:
  output:
     description: 'GitHub Actions markdown documents including Custom Actions and Reusable Workflows'
  agenda-ca:
    description: 'Agenda for Custom Actions markdown documents'
  output-ca:
    description: 'Custom Actions markdown documents'
  agenda-rw:
    description: 'Agenda for Reusable Workflows markdown documents'
  output-rw:
    description: 'Reusable Workflows markdown documents'

runs:
  using: 'node16'
  main: 'dist/index.js'
