name: "Caller Test"
on:
  push:
    branches:
      - main
    paths:
      - '*/action.yml'
      - '*/action.yaml'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '*/action.yml'
      - '*/action.yml'
      - '.github/workflows/*.yml'

jobs:
  test:
    uses: gizumon/github-actions-documenter/.github/workflows/github-actions-documenter.yml@main
    with:
      filepath: README.md

