name: "Caller Test"
on: pull_request

jobs:
  test:
    uses: gizumon/reusable-workflow-documentator/.github/workflows/reusable-workflow-documentator.yml@main
    with:
      filepath: .github/docs/reusable-workflow-doc.md
      overwrite: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
