name: "Caller Test"
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: gizumon/reusable-workflow-documentator/.github/workflows/reusable-workflow-documentator.yml@main
    with:
      filepath: .github/docs/reusable-workflow-doc.md
      overwrite: true
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
