name: "Caller Test"
on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: gizumon/reusable-workflow-documentator/.github/workflows/reusable-workflow-documentator.yml@main
    with:
      filepath: README.md
      overwrite: true
      make-pull-request: false
      github-base-url: "https://api.github.com"
