name: "Caller Test"
on:
  push:
    branches:
      - main
    paths:
      - 'action.yml'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  test:
    uses: gizumon/github-actions-documenter.github/workflows/github-actions-documenter.yml@main
    with:
      filepath: README.md
      overwrite: false
      make-pull-request: false
