# @example=### Example1: Basic example
# name: "Basic example"
# on:
#   pull_request:
#     paths:
#       - '.github/workflows/*.yml'
# jobs:
#   test:
#     uses: gizumon/github-actions-documenter/.github/workflows/github-actions-documenter.yml@main
#     with:
#       filepath: README.md

# @example=### Example2: Advanced example (with GHES support)
# name: "Advanced example"
# on:
#   pull_request:
#     paths:
#       - '.github/workflows/*.yml'
# jobs:
#   test:
#     uses: gizumon/github-actions-documenter/.github/workflows/github-actions-documenter.yml@main
#     with:
#       filepath: .github/docs/reusable-workflow-doc.md
#       overwrite: true
#       make-pull-request: true

# @note=### Support events
# - push
# - pull_request

name: Document Generate Reusable Workflow 
on:
  workflow_call:
    inputs:
      filepath:
        required: true
        type: string
        default: README.md
        description: "Filepath to write the generated reusable workflow document. (default: README.md)"
      overwrite:
        required: false
        type: boolean
        default: false
        description: "If true, overwrite the filepath file. (default: false)"
      make-pull-request:
        required: false
        type: boolean
        default: false
        description: "If true, make a pull request to ref branch. If false, directly push to ref branch. (default: false)"
      # github-base-url:
      #   type: string
      #   required: false
      #   default: "https://api.github.com"
      #   description: "GitHub Host domain (Support for GitHub Enterprise) (default: https://api.github.com)"
      # generate-only:
      #   required: false
      #   type: boolean
      #   default: false
      #   description: "Generate document and set output result only. (default: false)"
    outputs:
      output:
        description: "GitHub Actions markdown document (Reusable Workflow and Custom Actions)"
        value: "${{ jobs.documentation.outputs.output }}"

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  documentation:
    name: Generate reusable workflow document
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.documentator.outputs.output }}
    steps:
      - uses: actions/checkout@v2
      - name: Reusable Workflow Documentator Action
        id: documentator
        uses: gizumon/github-actions-documenter@main
        # with:
        #   filepath: ${{ inputs.filepath }}
        #   github-base-url: ${{ inputs.github-base-url }}
        #   overwrite: ${{ inputs.overwrite }}
        #   make-pull-request: ${{ inputs.make-pull-request }}
        #   generate-only: ${{ inputs.generate-only }}

      - name: Get branch name
        id: branch
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "branch name is ${{ github.head_ref }} ... (event:pull_request)"
            echo "::set-output name=name::${{ github.head_ref }}"
          else
            echo "branch name is ${{ github.ref_name }} ... (event:push)"
            echo "::set-output name=name::${{ github.ref_name }}"
          fi

      - name: Add a new file
        id: changes
        run: |
          git fetch
          git checkout -B ${{ steps.branch.outputs.name }} origin/${{ steps.branch.outputs.name }}
          if ${{ inputs.overwrite }}; then
            echo "Overwrite ${{ inputs.filepath }} file ..."
            echo '${{ steps.documentator.outputs.output }}' > ${{ inputs.filepath }}
          else
            startN=$(grep -n "@overwrite-anchor=start" ${{ inputs.filepath }} | awk -F ':' '{print $1}' | head -n 1)
            endN=$(grep -n "@overwrite-anchor=end" ${{ inputs.filepath }} | awk -F ':' '{print $1}' | head -n 1)
            if [ -n "${startN}" ]; then
              echo "Remove from ${startN} line to ${endN} line ..."
              if [ -n "${endN}" ]; then
                sed -e "$(( ${startN} - 1 )),${endN}d" ${{ inputs.filepath }} > temp.txt
              else
                sed -e "$(( ${startN} - 1 )),\$d" ${{ inputs.filepath }} > temp.txt
              fi
              cp -f temp.txt ${{ inputs.filepath }}
              rm -f temp.txt
            fi
            echo '${{ steps.documentator.outputs.output }}' >> ${{ inputs.filepath }}
          fi
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
          git add ${{ inputs.filepath }}

      - name: Update document
        if: ${{ steps.changes.outputs.count > 0 }}
        run: |
          echo "Changes files count = ${{ steps.changes.outputs.count }} ..."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "⚙ Updated ${{ inputs.filepath }} by github-actions-documenter"
          if ${{ inputs.make-pull-request == false }}; then
            echo "push to ${{ steps.branch.outputs.name }} ..."
            git push origin HEAD:${{ steps.branch.outputs.name }}
          fi
          echo ${{ (steps.changes.outputs.count > 0) && (inputs.make-pull-request == true) }}

      - name: Create New Pull Request If Needed
        if: ${{ (steps.changes.outputs.count > 0) && (inputs.make-pull-request == true) }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: "📝 Auto generated reusable workflow documentation"
          branch-suffix: timestamp
          commit-message: "⚙ Updated ${{ inputs.filepath }} by github-actions-documenter"
          body: 'Generated document ↓\n---\n${{ steps.documentator.outputs.output }}'
