# @example=### Simple Reusable workflow Call example 1
# name: "Simple example"
# on:
#   push:
#     branches: [ main ]
# jobs:
#   test:
#     uses: gizumon/reusable-workflow-documentator/.github/workflows/reusable-workflow-documentator.yml@main

# @example=### Reusable workflow Call example 2
# name: "Example"
# on:
#   push:
#     branches: [ main ]
# jobs:
#   test:
#     uses: gizumon/reusable-workflow-documentator/.github/workflows/reusable-workflow-documentator.yml@main
#     with:
#       filepath: .github/docs/reusable-workflow-doc.md
#       overwrite: false
#       github-base-url: "https://some-enterprise.github.com/api/v3"


name: Reusable Workflow Documentator
on:
  workflow_call:
    inputs:
      filepath:
        required: false
        type: string
        default: README.md
        description: "Filepath to write the reusable workflow documentation (default: README.md)"
      overwrite:
        required: false
        type: boolean
        default: false
        description: "Overwrite the file if it already exists (default: false)"
      github-base-url:
        type: string
        required: false
        default: "https://api.github.com"
        description: "GitHub Host domain (Support for GitHub Enterprise) (default: https://api.github.com)"

jobs:
  example_job1:
    name: example job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reusable Workflow Documentator Action
        id: documentator
        uses: ./
        with:
          make-pull-request: false
          github-base-url: ${{ inputs.github-base-url }}

      - name: Add a new file
        id: changes
        run: |
          if [ ${{ inputs.overwrite }} ]; then
            echo '${{ steps.documentator.outputs.document }}' > ${{ inputs.filepath }}
          else
            echo "${{ steps.documentator.outputs.document }}" >> ${{ inputs.filepath }}
          fi
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: Update document
        if: ${{ steps.changes.outputs.count }} > 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # git commit -m "Commit by Reusable workflow documentator"

      - name: Create New Pull Request If Needed
        if: steps.documentator.outputs.document != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Reusable Workflow Usage
          branch-suffix: timestamp
          commit-message: Commit by Reusable workflow documentator
          body: ${{ steps.documentator.outputs.document }}
