# @example=### Basic example
# name: "Simple example"
# on:
#   push:
#     branches: [ main ]
# jobs:
#   test:
#     uses: gizumon/reusable-workflow-documentator/.github/workflows/reusable-workflow-documentator.yml@main
#     with:
#       filepath: .github/docs/reusable-workflow-doc.md

# @example=### Advanced example (GHES support)
# name: "Example"
# on:
#   push:
#     branches: [ main ]
# jobs:
#   test:
#     uses: gizumon/reusable-workflow-documentator/.github/workflows/reusable-workflow-documentator.yml@main
#     with:
#       filepath: .github/docs/reusable-workflow-doc.md
#       overwrite: false
#       make-pull-request: true
#       github-base-url: "https://some-enterprise.github.com/api/v3"

name: Reusable Workflow Documentator
on:
  workflow_call:
    inputs:
      filepath:
        required: true
        type: string
        default: README.md
        description: "Filepath to write the reusable workflow documentation. (default: README.md)"
      github-base-url:
        type: string
        required: false
        default: "https://api.github.com"
        description: "GitHub Host domain (Support for GitHub Enterprise) (default: https://api.github.com)"
      overwrite:
        required: false
        type: boolean
        default: false
        description: "If true, overwrite the filepath file. (default: false)"
      make-pull-request:
        required: false
        type: boolean
        default: false
        description: "If true, make a pull request to ref branch. If false, directly push generated doc to ref branch. (default: false)"
      # generate-only:
      #   required: false
      #   type: boolean
      #   default: false
      #   description: "Generate document and set output result only. (default: false)"
    secrets:
      ACCESS_TOKEN:
        required: true
        description: "GitHub Personal Access Token"
env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  example_job1:
    name: example job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reusable Workflow Documentator Action
        id: documentator
        uses: ./
        with:
          filepath: ${{ inputs.filepath }}
          github-base-url: ${{ inputs.github-base-url }}
          # overwrite: ${{ inputs.overwrite }}
          # make-pull-request: ${{ inputs.make-pull-request }}
          # generate-only: ${{ inputs.generate-only }}

      - name: Add a new file
        id: changes
        run: |
          if [ ${{ inputs.overwrite }} ]; then
            echo '${{ steps.documentator.outputs.document }}' > ${{ inputs.filepath }}
          else
            num=$(grep -n "@over-write-anchor" ${{ inputs.filepath }} | awk -F ':' '{print $1}' | head -n 1)
            if [ -z "${num}" ]; then
              # Remove the lines that was generated by the previous action
              sed -e '1,$d' .github/docs/reusable-workflow-doc.md
            fi
            echo "${{ steps.documentator.outputs.document }}" >> ${{ inputs.filepath }}
          fi
          git add -N .
          git status
          git diff --name-only
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: Update document
        if: ${{ steps.changes.outputs.count }} > 0 && ${{ ! inputs.make-pull-request }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "⚙ Commit by Reusable workflow documentator"

      - name: Create New Pull Request If Needed
        if: ${{ steps.changes.outputs.count }} > 0 && ${{ inputs.make-pull-request }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: Reusable Workflow Usage
          branch-suffix: timestamp
          commit-message: Commit by Reusable workflow documentator
          body: ${{ steps.documentator.outputs.document }}
