name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install -g pnpm
      - run: |
          pnpm install
      - run: |
          pnpm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run action.yml
        uses: ./
        id: test
        with:
          milliseconds: 1000
      - name: Outputs
        run:
          echo "Output\n ${{ steps.test.outputs.output }}"
          echo "Custom Actions Agenda\n ${{ steps.test.outputs.agenda-ca }}"
          echo "Custom Actions Output\n ${{ steps.test.outputs.output-ca }}"
          echo "Reusable Workflow Agenda\n ${{ steps.test.outputs.agenda-rw }}"
          echo "Reusable Workflow Output\n ${{ steps.test.outputs.output-rw }}"
